// data/agencias.ts

import { AgencyDTO } from "../interface/Agency";

const agencia1: AgencyDTO = {
  id: 1,
  name: "Altos del Norte",
  description: "Altos del Norte es una inmobiliaria con más de 20 años de experiencia dedicada a ofrecer las mejores opciones en casas familiares en la región norte del país. Nos especializamos en brindar atención personalizada y soluciones a medida para cada cliente, acompañándote en todo el proceso de compra, venta o alquiler. Nuestra prioridad es ayudarte a encontrar el hogar ideal que se adapte a tus necesidades y presupuesto, garantizando transparencia, confianza y profesionalismo en cada operación. Contamos con un amplio catálogo de propiedades en barrios privados y zonas residenciales, con servicios de asesoramiento legal y financiero para que tu inversión sea segura y rentable. Confía en Altos del Norte para convertir tu sueño de una casa propia en una realidad.",
  cuit_dni_m: "30-12345678-1",
  customization: {
    id: 1,
    logoImage: "https://static.vecteezy.com/system/resources/thumbnails/023/495/220/small/real-estate-logo-design-png.png",
    information: "Contamos con más de 20 años de experiencia en el rubro.",
    mainColors: "#1E3A8A",
    banner: "https://www.blogdelfotografo.com/wp-content/uploads/2015/07/15286446368_3266e9b8ab_k.jpg",
    navbarColor: "#1D4ED8",
    buttonColor: "#2563EB",
    backgroundColor: "#EFF6FF",
    secondaryColor: "#ff0000",
  },
  agentUser: {
    id: 10,
    name: "María",
    surname: "Gutiérrez",
    email: "maria@altosdelnorte.com",
    phone: "3517474105",
    rol: "User",
  },
  properties: [
    {
      id: 101,
      name: "Casa en barrio privado",
      type_of_property: "house",
      status: "available",
      type: "sell",
      address: "Av. Perón 123",
      city: "Tafí Viejo",
      price: 150000,
      m2: 230,
      bathroom: 22,
      rooms: 4,
      description: "Casa moderna con pileta, seguridad 24hs y cochera doble.",
      date: "2024-05-15",
      images: [
        { id: 1, file: "https://img.freepik.com/vector-gratis/casa-encantadora-ilustracion-arbol_1308-176337.jpg?semt=ais_hybrid&w=740", description: "/images/casa1.jpg" },
        { id: 2, file: "https://img.freepik.com/vector-gratis/ilustracion-encantadora-casa-dibujos-animados_1308-176057.jpg?semt=ais_hybrid&w=740", description: "/images/casa1b.jpg" },
        { id: 111, file: "https://img.freepik.com/vector-gratis/ilustracion-encantadora-casa-dibujos-animados_1308-176057.jpg?semt=ais_hybrid&w=740", description: "/images/casa1b.jpg" },
        { id: 22, file: "https://img.freepik.com/vector-gratis/ilustracion-encantadora-casa-dibujos-animados_1308-176057.jpg?semt=ais_hybrid&w=740", description: "/images/casa1b.jpg" },
      ],
      agencyId: 1,
    },
    {
      id: 102,
      name: "Departamento en el centro",
      type_of_property: "appartment",
      status: "available",
      type: "rent",
      address: "Belgrano 456",
      city: "San Miguel de Tucumán",
      price: 95000,
      m2: 90,
      bathroom: 1,
      rooms: 2,
      description: "Departamento céntrico, ideal para estudiantes.",
      date: "2024-05-20",
      images: [
        { id: 3, file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX5h6077ZXoIEQfLniOnjdRaEScvcDSsyohQ&s", description: "/images/depto1.jpg" },
      ],
      agencyId: 1,
    },
    {
      id: 103,
      name: "Casa en Yerba Buena",
      type_of_property: "house",
      status: "available",
      type: "sell",
      address: "Ruta 9 KM 5",
      city: "Yerba Buena",
      price: 60000,
      m2: 500,
      bathroom: 0,
      rooms: 0,
      description: "Terreno ideal para inversión, listo para escriturar.",
      date: "2024-06-01",
      images: [
        { id: 4, file: "https://imgix.cosentino.com/es/wp-content/uploads/2023/07/Lumire-70-Facade-MtWaverley-vic-1.jpg?auto=format%2Ccompress&ixlib=php-3.3.0", description: "/images/lote1.jpg" },
      ],
      agencyId: 1,
    },
    {
  id: 104,
  name: "Casa en Lomas de Tafí",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Calle 8, Mz B",
  city: "Tafí Viejo",
  price: 78000,
  m2: 120,
  bathroom: 2,
  rooms: 3,
  description: "Casa lista para habitar, con patio y parrilla.",
  date: "2024-06-02",
  images: [
    { id: 5, file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlASv5RR9bFy3o-fNjlDgNQbJvCvpljbZv5A&s", description: "Frente de la casa" },
  ],
  agencyId: 1,
},
{
  id: 105,
  name: "Lote en Las Talitas",
  type_of_property: "land",
  status: "available",
  type: "sell",
  address: "Calle 12 y Av. San Ramón",
  city: "Las Talitas",
  price: 35000,
  m2: 300,
  bathroom: 0,
  rooms: 0,
  description: "Terreno en zona tranquila y en desarrollo.",
  date: "2024-06-03",
  images: [
    { id: 6, file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpT_yUYUitr68VUb3IDTT-yxsCjFG0DnQGg&s", description: "Vista del terreno" },
  ],
  agencyId: 1,
},
{
  id: 106,
  name: "Departamento amoblado",
  type_of_property: "appartment",
  status: "available",
  type: "rent",
  address: "Maipú 222",
  city: "San Miguel de Tucumán",
  price: 110000,
  m2: 70,
  bathroom: 1,
  rooms: 2,
  description: "Alquiler temporal, totalmente equipado.",
  date: "2024-06-04",
  images: [
    { id: 7, file: "https://cdn.prod.website-files.com/61e9b342b016364181c41f50/62a014dd84797690c528f25e_38.jpg", description: "Living comedor" },
  ],
  agencyId: 1,
},
{
  id: 107,
  name: "Casa con jardín",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Chile 789",
  city: "San Miguel de Tucumán",
  price: 92000,
  m2: 150,
  bathroom: 2,
  rooms: 4,
  description: "Casa familiar con jardín al fondo y galería.",
  date: "2024-06-05",
  images: [
    { id: 8, file: "https://content.elmueble.com/medio/2020/05/04/00505029_20d81336_2000x1333.jpg", description: "Jardín trasero" },
  ],
  agencyId: 1,
},
{
  id: 108,
  name: "Casa en Country",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Country El Rodeo",
  city: "Yerba Buena",
  price: 230000,
  m2: 300,
  bathroom: 3,
  rooms: 5,
  description: "Casa premium con pileta, quincho y seguridad.",
  date: "2024-06-06",
  images: [
    { id: 9, file: "https://resizer.glanacion.com/resizer/v2/cuanto-cuesta-construir-una-casa-de-315-m2-en-un-EZME34UZ7BHE5EDY2QO4KMMWH4.JPG?auth=64bf5b516d8884236ed9deed93a4bf0f73417734882ca1b3ca8e18915424fde1&width=1280&height=854&quality=70&smart=true", description: "Pileta y parque" },
  ],
  agencyId: 1,
},
{
  id: 109,
  name: "Monoambiente céntrico",
  type_of_property: "appartment",
  status: "available",
  type: "rent",
  address: "Mendoza 1125",
  city: "San Miguel de Tucumán",
  price: 85000,
  m2: 35,
  bathroom: 1,
  rooms: 1,
  description: "Ideal para estudiantes o profesionales.",
  date: "2024-06-07",
  images: [
    { id: 10, file: "https://images.homify.com/v1548695799/p/photo/image/2890874/4-Andr%C3%A9a_11_1.jpg", description: "Ambiente único" },
  ],
  agencyId: 1,
},
{
  id: 110,
  name: "Lote en Tafí del Valle",
  type_of_property: "land",
  status: "available",
  type: "sell",
  address: "Camino al Infiernillo",
  city: "Tafí del Valle",
  price: 120000,
  m2: 800,
  bathroom: 0,
  rooms: 0,
  description: "Terreno en altura con vista panorámica.",
  date: "2024-06-08",
  images: [
    { id: 11, file: "https://revistaestilopropio.com/wp-content/uploads/2018/04/IMG_9468-Copy-2-1024x683.jpg", description: "Vista al valle" },
  ],
  agencyId: 1,
},
{
  id: 111,
  name: "Departamento 3 habitaciones",
  type_of_property: "appartment",
  status: "available",
  type: "rent",
  address: "Catamarca 321",
  city: "San Miguel de Tucumán",
  price: 135000,
  m2: 100,
  bathroom: 2,
  rooms: 3,
  description: "Ideal para familia, cercano a colegios.",
  date: "2024-06-09",
  images: [
    { id: 12, file: "https://d1v2p1s05qqabi.cloudfront.net/12360036/1730126337.jpg", description: "Cocina comedor" },
  ],
  agencyId: 1,
},
{
  id: 112,
  name: "Casa con local comercial",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Av. Colón 555",
  city: "San Miguel de Tucumán",
  price: 170000,
  m2: 250,
  bathroom: 2,
  rooms: 4,
  description: "Casa + local con renta activa, zona de alto tránsito.",
  date: "2024-06-10",
  images: [
    { id: 13, file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdtOIvmdfg4hTesrXdAsC_x7hahxGw75ivJw&s", description: "Frente con vidriera" },
  ],
  agencyId: 1,
},
{
  id: 113,
  name: "Casa en El Manantial",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Calle La Rinconada",
  city: "El Manantial",
  price: 88000,
  m2: 140,
  bathroom: 2,
  rooms: 3,
  description: "Zona residencial, casa con patio y cochera.",
  date: "2024-06-11",
  images: [
    { id: 14, file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTQ4bf0PBXzKMyKOF5-AJQCgfrbHPiz1bsMw&s", description: "Exterior moderno" },
  ],
  agencyId: 1,
},
{
  id: 114,
  name: "Lote esquina",
  type_of_property: "land",
  status: "available",
  type: "sell",
  address: "Esquina Italia y Rivadavia",
  city: "Yerba Buena",
  price: 50000,
  m2: 400,
  bathroom: 0,
  rooms: 0,
  description: "Ideal para local comercial o duplex.",
  date: "2024-06-12",
  images: [
    { id: 15, file: "https://inmobiliariacdelcastillo.com.ar/wp-content/uploads/2025/02/mapa-lote-esquina-cris.jpg", description: "Ubicación privilegiada" },
  ],
  agencyId: 1,
},
{
  id: 115,
  name: "Casa moderna con pileta",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Barrio Privado La Arboleda",
  city: "Yerba Buena",
  price: 245000,
  m2: 280,
  bathroom: 3,
  rooms: 4,
  description: "Diseño minimalista, gran jardín y pileta.",
  date: "2024-06-13",
  images: [
    { id: 16, file: "https://images.homify.com/v1481562165/p/photo/image/1734022/26_02_3009_NORDELTA_ISLA_CIBA_045.jpg", description: "Moderna y luminosa" },
  ],
  agencyId: 1,
},
{
  id: 116,
  name: "Departamento tipo dúplex",
  type_of_property: "appartment",
  status: "available",
  type: "sell",
  address: "La Rioja 832",
  city: "San Miguel de Tucumán",
  price: 112000,
  m2: 95,
  bathroom: 2,
  rooms: 3,
  description: "Dúplex con terraza, 2 baños y cochera.",
  date: "2024-06-14",
  images: [
    { id: 17, file: "https://beca.pe/wp-content/uploads/2023/12/d195186plex-1080x675.webp", description: "Living con escalera" },
  ],
  agencyId: 1,
},
{
  id: 117,
  name: "Casa a estrenar",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Pasaje Las Rosas 1120",
  city: "Tafí Viejo",
  price: 78000,
  m2: 110,
  bathroom: 2,
  rooms: 3,
  description: "Lista para escriturar, diseño moderno y funcional.",
  date: "2024-06-15",
  images: [
    { id: 18, file: "https://vgb.com.ar/inmobiliarias/wp-content/uploads/2020/07/Casa-a-estrenar-en-Villa-General-Belgrano-FAL008-1.jpg", description: "Fachada minimalista" },
  ],
  agencyId: 1,
},
{
  id: 118,
  name: "Lote en zona industrial",
  type_of_property: "land",
  status: "available",
  type: "sell",
  address: "Acceso Sur",
  city: "San Miguel de Tucumán",
  price: 98000,
  m2: 2000,
  bathroom: 0,
  rooms: 0,
  description: "Ideal para galpón o centro logístico.",
  date: "2024-06-16",
  images: [
    { id: 19, file: "https://imgar.zonapropcdn.com/avisos/1/00/55/98/94/38/360x266/1969582590.jpg?isFirstImage=true", description: "Terreno amplio y plano" },
  ],
  agencyId: 1,
}

  ],
};

const agencia2: AgencyDTO = {
  id: 2,
  name: "Patagonia Hogares",
  description: "Encontrá tu hogar en el sur del país, entre montañas y lagos.",
  cuit_dni_m: "27-87654321-0",
  customization: {
    id: 2,
    logoImage: "/logos/patagonia-hogares.png",
    information: "Expertos en propiedades de Bariloche, El Bolsón y alrededores.",
    mainColors: "#065F46",
    banner: "#34D399",
    navbarColor: "#047857",
    buttonColor: "#10B981",
    backgroundColor: "#ECFDF5",
    secondaryColor: "#064E3B",
  },
  agentUser: {
    id: 11,
    name: "Carlos",
    surname: "Méndez",
    email: "carlos@patagoniahogares.com",
    phone: "294-789-4561",
    rol: "User",
  },
  properties: [
    {
      id: 201,
      name: "Cabaña en el bosque",
      type_of_property: "garage",
      status: "available",
      type: "sell",
      address: "Lago Gutiérrez s/n",
      city: "Bariloche",
      price: 180000,
      m2: 120,
      bathroom: 1,
      rooms: 3,
      description: "Encantadora cabaña con vista al lago y chimenea.",
      date: "2024-05-10",
      images: [
        { id: 5, file: "/images/cabana1.jpg", description: "/images/cabana1.jpg" },
      ],
      agencyId: 2,
    },
    {
      id: 202,
      name: "Casa moderna en El Bolsón",
      type_of_property: "house",
      status: "available",
      type: "sell",
      address: "Av. Los Notros 789",
      city: "El Bolsón",
      price: 130000,
      m2: 180,
      bathroom: 2,
      rooms: 4,
      description: "Ideal para familia grande, patio, parrilla y garage.",
      date: "2024-05-18",
      images: [
        { id: 6, file: "/images/casa2.jpg", description: "/images/casa2.jpg" },
      ],
      agencyId: 2,
    },
    {
      id: 203,
      name: "Terreno con vista a la montaña",
      type_of_property: "farmhouse",
      status: "available",
      type: "sell",
      address: "Calle 5",
      city: "Villa La Angostura",
      price: 75000,
      m2: 800,
      bathroom: 0,
      rooms: 0,
      description: "800m² en zona alta, cerca de rutas y servicios.",
      date: "2024-06-01",
      images: [
        { id: 7, file: "/images/terreno2.jpg", description: "/images/terreno2.jpg" },
      ],
      agencyId: 2,
    },
  ],
};

const agencia3: AgencyDTO = {
  id: 3,
  name: "Costa Dorada Inmuebles",
  description: "Especialistas en propiedades frente al mar y casas de descanso.",
  cuit_dni_m: "33-98765432-5",
  customization: {
    id: 3,
    logoImage: "/logos/costa-dorada.png",
    information: "Más de 15 años ayudándote a encontrar el hogar ideal en la costa.",
    mainColors: "#0C4A6E",
    banner: "#0284C7",
    navbarColor: "#0369A1",
    buttonColor: "#0EA5E9",
    backgroundColor: "#E0F2FE",
    secondaryColor: "#075985",
  },
  agentUser: {
    id: 12,
    name: "Lucía",
    surname: "Fernández",
    email: "lucia@costadorada.com",
    phone: "2261-555-123",
    rol: "User",
  },
  properties: [
    {
      id: 301,
      name: "Departamento frente al mar",
      type_of_property: "appartment",
      status: "available",
      type: "sell",
      address: "Av. Costanera 150",
      city: "Mar del Plata",
      price: 200000,
      m2: 100,
      bathroom: 2,
      rooms: 3,
      description: "Hermoso departamento con balcón y vista panorámica al mar.",
      date: "2024-06-10",
      images: [
        { id: 11, file: "/images/depto-mar.jpg", description: "/images/depto-mar.jpg" },
        { id: 12, file: "/images/depto-mar2.jpg", description: "/images/depto-mar2.jpg" },
      ],
      agencyId: 3,
    },
    {
      id: 302,
      name: "Casa de descanso en Pinamar",
      type_of_property: "house",
      status: "available",
      type: "rent",
      address: "Calle Los Pinos 500",
      city: "Pinamar",
      price: 120000,
      m2: 150,
      bathroom: 2,
      rooms: 4,
      description: "Casa cómoda y equipada para vacaciones familiares.",
      date: "2024-06-15",
      images: [
        { id: 13, file: "/images/casa-pinamar.jpg", description: "/images/casa-pinamar.jpg" },
      ],
      agencyId: 3,
    },
    {
      id: 303,
      name: "Lote en zona residencial",
      type_of_property: "house",
      status: "available",
      type: "sell",
      address: "Boulevard Principal 100",
      city: "Miramar",
      price: 70000,
      m2: 600,
      bathroom: 0,
      rooms: 0,
      description: "Amplio lote ideal para construir tu casa soñada.",
      date: "2024-06-20",
      images: [
        { id: 14, file: "/images/lote-miramar.jpg", description: "/images/lote-miramar.jpg" },
      ],
      agencyId: 3,
    },
    {
  id: 304,
  name: "Casa estilo colonial",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "San Martín 450",
  city: "Salta",
  price: 180000,
  m2: 220,
  bathroom: 3,
  rooms: 5,
  description: "Casa amplia con jardín, quincho y cochera doble en el centro de Salta.",
  date: "2024-06-18",
  images: [
    { id: 15, file: "/images/casa-salta.jpg", description: "Fachada colonial con jardín" },
  ],
  agencyId: 3,
},
{
  id: 305,
  name: "Departamento moderno en Palermo",
  type_of_property: "appartment",
  status: "available",
  type: "rent",
  address: "Godoy Cruz 2500",
  city: "Buenos Aires",
  price: 95000,
  m2: 75,
  bathroom: 1,
  rooms: 2,
  description: "Depto en torre moderna con amenities y seguridad 24hs.",
  date: "2024-06-12",
  images: [
    { id: 16, file: "/images/depto-palermo.jpg", description: "Vista al balcón de Palermo" },
    { id: 17, file: "/images/depto-palermo2.jpg", description: "Living moderno" },
  ],
  agencyId: 3,
},
{
  id: 306,
  name: "Cabaña en las sierras",
  type_of_property: "house",
  status: "available",
  type: "rent",
  address: "Camino a las Altas Cumbres km 12",
  city: "Villa Carlos Paz",
  price: 80000,
  m2: 90,
  bathroom: 1,
  rooms: 2,
  description: "Cabaña rústica con pileta y vista a las sierras.",
  date: "2024-06-08",
  images: [
    { id: 18, file: "/images/cabana-carlospaz.jpg", description: "Cabaña con entorno natural" },
  ],
  agencyId: 3,
},
{
  id: 307,
  name: "Lote frente al río",
  type_of_property: "appartment",
  status: "available",
  type: "sell",
  address: "Ruta 11 km 5",
  city: "San Pedro",
  price: 95000,
  m2: 1000,
  bathroom: 0,
  rooms: 0,
  description: "Terreno único con vista al río Paraná, ideal para casa de fin de semana.",
  date: "2024-06-05",
  images: [
    { id: 19, file: "/images/lote-sanpedro.jpg", description: "Vista al río desde el lote" },
  ],
  agencyId: 3,
},
{
  id: 308,
  name: "Departamento en Nueva Córdoba",
  type_of_property: "appartment",
  status: "available",
  type: "sell",
  address: "Obispo Trejo 1234",
  city: "Córdoba",
  price: 135000,
  m2: 85,
  bathroom: 2,
  rooms: 3,
  description: "Departamento céntrico con balcón, cochera y excelente iluminación natural.",
  date: "2024-06-17",
  images: [
    { id: 20, file: "/images/depto-cordoba.jpg", description: "Living y comedor luminosos" },
    { id: 21, file: "/images/depto-cordoba2.jpg", description: "Vista desde el balcón" },
  ],
  agencyId: 3,
},
{
  id: 309,
  name: "Casa con parque y pileta",
  type_of_property: "house",
  status: "available",
  type: "sell",
  address: "Av. del Sol 2200",
  city: "Merlo",
  price: 165000,
  m2: 180,
  bathroom: 2,
  rooms: 4,
  description: "Ideal para familia. Hermoso parque, pileta, quincho y 2 cocheras.",
  date: "2024-06-13",
  images: [
    { id: 22, file: "/images/casa-merlo.jpg", description: "Jardín con pileta" },
  ],
  agencyId: 3,
},
{
  id: 310,
  name: "Lote en Las Grutas",
  type_of_property: "land",
  status: "available",
  type: "sell",
  address: "Las Gaviotas 600",
  city: "Las Grutas",
  price: 60000,
  m2: 500,
  bathroom: 0,
  rooms: 0,
  description: "Terreno plano a 4 cuadras del mar. Ideal para proyecto turístico.",
  date: "2024-06-14",
  images: [
    { id: 23, file: "/images/lote-grutas.jpg", description: "Terreno amplio cerca de la playa" },
  ],
  agencyId: 3,
},
{
  id: 311,
  name: "Monoambiente en Recoleta",
  type_of_property: "appartment",
  status: "available",
  type: "rent",
  address: "Uriburu 1050",
  city: "Buenos Aires",
  price: 85000,
  m2: 40,
  bathroom: 1,
  rooms: 1,
  description: "Monoambiente totalmente amueblado, ideal para estudiante o pareja.",
  date: "2024-06-09",
  images: [
    { id: 24, file: "/images/mono-recoleta.jpg", description: "Ambiente único con cocina integrada" },
  ],
  agencyId: 3,
},
{
  id: 312,
  name: "Cabaña en El Bolsón",
  type_of_property: "house",
  status: "available",
  type: "rent",
  address: "Camino a Mallín Ahogado",
  city: "El Bolsón",
  price: 70000,
  m2: 95,
  bathroom: 1,
  rooms: 3,
  description: "Cabaña en entorno natural, con estufa a leña y galería con vista a la cordillera.",
  date: "2024-06-16",
  images: [
    { id: 25, file: "/images/cabana-bolson.jpg", description: "Exterior de la cabaña en bosque patagónico" },
  ],
  agencyId: 3,
}

  ],
};

export const agencias: AgencyDTO[] = [agencia1, agencia2, agencia3];

// // Función para slugificar nombres (reemplaza espacios por guiones, pasa a minúsculas)
// export function slugify(name: string) {
//   return name.toLowerCase().replace(/\s+/g, "-");
// }
