
import "../../app/globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/Footer/Footer";
import ChatbotPrueba from "@/components/ChatBot/chatbot";

export const metadata: Metadata = {
  title: "KassApp",
  description: "Generated by create next app",
  icons: "iconoKasapp.png",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,

};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
        <div className="bg-white h-16">
        <Navbar />
        </div>

        {children}
        {/* <ChatbotPrueba /> */}
        <Footer />
      </>
      
  );
}
